services:
  - type: web
    name: dashboard_project
    env: python
    pythonVersion: 3.11.0
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard_project.wsgi:application"
