# Generated by Django 4.2.7 on 2025-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaHumanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('localidad', models.TextField()),
                ('distrito', models.TextField()),
                ('departamento', models.TextField()),
                ('evento', models.TextField()),
                ('kit_b', models.IntegerField(default=0)),
                ('kit_a', models.IntegerField(default=0)),
                ('chapa_fibrocemento', models.IntegerField(default=0)),
                ('chapa_zinc', models.IntegerField(default=0)),
                ('colchones', models.IntegerField(default=0)),
                ('frazadas', models.IntegerField(default=0)),
                ('terciadas', models.IntegerField(default=0)),
                ('puntales', models.IntegerField(default=0)),
                ('carpas_plasticas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Asistencia Humanitaria',
                'verbose_name_plural': 'Asistencias Humanitarias',
                'db_table': 'asistencia_humanitaria',
            },
        ),
    ]
